#!/usr/bin/env python3
"""Summarize and plot core 100 ns MD analyses.

The script reads GROMACS XVG files generated by 40_run_md_core_analysis.sh,
computes block statistics, and creates publication-style PNG/SVG/PDF figures.
"""

from __future__ import annotations

import math
import re
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib as mpl
mpl.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator

try:
    from scipy.stats import t as student_t
except Exception:  # pragma: no cover
    student_t = None


ROOT = Path(__file__).resolve().parents[1]
SYSTEMS_DIR = ROOT / "12_md_candidates" / "05_gromacs_systems"
OUT = ROOT / "12_md_candidates" / "06_md_analysis"


@dataclass(frozen=True)
class SystemInfo:
    pair_id: str
    label: str
    protein: str
    ligand: str
    color: str


SYSTEMS = [
    SystemInfo("MAPK14_3HLL__L01_Pelargonidin", "MAPK14-Pelargonidin", "MAPK14", "Pelargonidin", "#0072B2"),
    SystemInfo("MAPK14_3HLL__L07_Thyroxine", "MAPK14-Thyroxine", "MAPK14", "Thyroxine", "#D55E00"),
    SystemInfo(
        "PTPRC_1YGU__L03_5_7_dihydroxy_2_phenyl_4H_chromen_4_one",
        "PTPRC-Flavone",
        "PTPRC",
        "5,7-dihydroxyflavone",
        "#009E73",
    ),
    SystemInfo(
        "BCL2_8HTS__L03_5_7_dihydroxy_2_phenyl_4H_chromen_4_one",
        "BCL2-Flavone",
        "BCL2",
        "5,7-dihydroxyflavone",
        "#CC79A7",
    ),
]


METRICS = {
    "complex_rmsd": {
        "file": "02_xvg_metrics/rmsd_complex_protein_ligand.xvg",
        "title": "Complex RMSD",
        "ylabel": "RMSD (nm)",
        "kind": "time",
    },
    "protein_rmsd": {
        "file": "02_xvg_metrics/rmsd_protein_backbone.xvg",
        "title": "Protein backbone RMSD",
        "ylabel": "RMSD (nm)",
        "kind": "time",
    },
    "ligand_rmsd": {
        "file": "02_xvg_metrics/rmsd_ligand_backbone_aligned.xvg",
        "title": "Ligand RMSD",
        "ylabel": "RMSD (nm)",
        "kind": "time",
    },
    "rg": {
        "file": "02_xvg_metrics/rg_protein.xvg",
        "title": "Radius of gyration",
        "ylabel": "Rg (nm)",
        "kind": "time",
    },
    "sasa": {
        "file": "02_xvg_metrics/sasa_protein_total.xvg",
        "title": "Protein SASA",
        "ylabel": "SASA (nm$^2$)",
        "kind": "time",
    },
    "hbond": {
        "file": "03_hbond_strict/hbond_protein_ligand_num.xvg",
        "title": "Protein-ligand H-bonds",
        "ylabel": "H-bonds (count)",
        "kind": "time",
    },
    "rmsf": {
        "file": "02_xvg_metrics/rmsf_calpha_by_residue.xvg",
        "title": "C-alpha RMSF",
        "ylabel": "RMSF (nm)",
        "kind": "residue",
    },
}


def configure_style() -> None:
    mpl.rcParams.update(
        {
            "font.family": "Arial",
            "font.size": 8.5,
            "axes.labelsize": 9,
            "axes.titlesize": 9.5,
            "xtick.labelsize": 8,
            "ytick.labelsize": 8,
            "legend.fontsize": 7.4,
            "axes.linewidth": 0.8,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "svg.fonttype": "none",
            "figure.dpi": 300,
            "savefig.dpi": 600,
        }
    )


def read_xvg(path: Path) -> pd.DataFrame:
    rows: list[list[float]] = []
    for line in path.read_text(errors="ignore").splitlines():
        s = line.strip()
        if not s or s.startswith(("#", "@")):
            continue
        try:
            rows.append([float(x) for x in s.split()])
        except ValueError:
            continue
    if not rows:
        raise ValueError(f"No numeric XVG rows in {path}")
    df = pd.DataFrame(rows)
    if df.shape[1] < 2:
        raise ValueError(f"Expected at least two columns in {path}")
    return df


def metric_series(sys_info: SystemInfo, metric: str) -> pd.DataFrame:
    path = SYSTEMS_DIR / sys_info.pair_id / "03_analysis" / METRICS[metric]["file"]
    df = read_xvg(path)
    value_col = 1
    x = df.iloc[:, 0].astype(float).copy()
    if METRICS[metric]["kind"] == "time" and float(x.max()) > 1000.0:
        x = x / 1000.0
    return pd.DataFrame({"x": x, "value": df.iloc[:, value_col]})


def rolling_mean(y: pd.Series, x: pd.Series, window_ns: float = 1.0) -> pd.Series:
    if len(x) < 3:
        return y
    dt = float(np.nanmedian(np.diff(x)))
    if not np.isfinite(dt) or dt <= 0:
        return y
    window = max(1, int(round(window_ns / dt)))
    return y.rolling(window=window, center=True, min_periods=max(1, window // 5)).mean()


def ci95_from_blocks(values: np.ndarray) -> tuple[float, float, float, float]:
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]
    if len(values) == 0:
        return (np.nan, np.nan, np.nan, np.nan)
    mean = float(np.mean(values))
    sd = float(np.std(values, ddof=1)) if len(values) > 1 else 0.0
    sem = float(sd / math.sqrt(len(values))) if len(values) > 0 else np.nan
    if len(values) > 1:
        mult = float(student_t.ppf(0.975, len(values) - 1)) if student_t is not None else 1.96
        ci = mult * sem
    else:
        ci = np.nan
    return mean, sd, sem, ci


def full_and_block_stats(sys_info: SystemInfo, metric: str, data: pd.DataFrame) -> tuple[dict, list[dict]]:
    time = data["x"].to_numpy()
    values = data["value"].to_numpy()

    full = values[np.isfinite(values)]
    final = data[(data["x"] >= 80.0) & (data["x"] <= 100.0)]["value"].to_numpy()
    full_mean = float(np.nanmean(full))
    full_sd = float(np.nanstd(full, ddof=1)) if len(full) > 1 else 0.0

    blocks = []
    block_means = []
    for start in np.arange(80.0, 100.0, 5.0):
        end = start + 5.0
        subset = data[(data["x"] >= start) & (data["x"] < end)]["value"].to_numpy()
        subset = subset[np.isfinite(subset)]
        if len(subset):
            bmean = float(np.mean(subset))
            bsd = float(np.std(subset, ddof=1)) if len(subset) > 1 else 0.0
            block_means.append(bmean)
        else:
            bmean = np.nan
            bsd = np.nan
        blocks.append(
            {
                "pair_id": sys_info.pair_id,
                "system": sys_info.label,
                "protein": sys_info.protein,
                "ligand": sys_info.ligand,
                "metric": metric,
                "block_start_ns": start,
                "block_end_ns": end,
                "n_frames": int(len(subset)),
                "mean": bmean,
                "sd": bsd,
            }
        )

    final_mean, final_block_sd, final_sem, final_ci95 = ci95_from_blocks(np.asarray(block_means))
    return (
        {
            "pair_id": sys_info.pair_id,
            "system": sys_info.label,
            "protein": sys_info.protein,
            "ligand": sys_info.ligand,
            "metric": metric,
            "n_frames_total": int(len(full)),
            "full_0_100ns_mean": full_mean,
            "full_0_100ns_sd": full_sd,
            "final_80_100ns_frame_mean": float(np.nanmean(final)) if len(final) else np.nan,
            "final_80_100ns_block_mean": final_mean,
            "final_80_100ns_block_sd": final_block_sd,
            "final_80_100ns_block_sem": final_sem,
            "final_80_100ns_block_95ci": final_ci95,
            "n_blocks": int(np.sum(np.isfinite(block_means))),
            "block_size_ns": 5.0,
        },
        blocks,
    )


def clean_axis(ax: plt.Axes) -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.grid(True, color="#E6E8EB", linewidth=0.55, alpha=0.9)
    ax.set_axisbelow(True)


def save_figure(fig: plt.Figure, out_stem: Path) -> None:
    out_stem.parent.mkdir(parents=True, exist_ok=True)
    for ext in [".png", ".svg", ".pdf"]:
        fig.savefig(out_stem.with_suffix(ext), bbox_inches="tight")


def plot_core_timeseries(all_data: dict[tuple[str, str], pd.DataFrame]) -> None:
    metrics = ["complex_rmsd", "protein_rmsd", "ligand_rmsd", "rg", "sasa", "hbond"]
    fig, axes = plt.subplots(3, 2, figsize=(7.2, 7.6), sharex=True)
    axes = axes.ravel()
    for ax, metric in zip(axes, metrics):
        for sys_info in SYSTEMS:
            data = all_data[(sys_info.pair_id, metric)]
            smooth = rolling_mean(data["value"], data["x"], 1.0)
            ax.plot(data["x"], smooth, color=sys_info.color, lw=1.45, label=sys_info.label)
        ax.set_title(METRICS[metric]["title"], pad=5)
        ax.set_ylabel(METRICS[metric]["ylabel"])
        clean_axis(ax)
        if metric == "hbond":
            ax.yaxis.set_major_locator(MaxNLocator(integer=True))
    for ax in axes[-2:]:
        ax.set_xlabel("Time (ns)")
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=2, frameon=False, bbox_to_anchor=(0.5, -0.01))
    fig.subplots_adjust(hspace=0.34, wspace=0.28, bottom=0.15)
    save_figure(fig, OUT / "04_figures" / "01_core_timeseries_1ns_rolling_mean")
    plt.close(fig)


def plot_individual_timeseries(all_data: dict[tuple[str, str], pd.DataFrame]) -> None:
    metrics = ["complex_rmsd", "protein_rmsd", "ligand_rmsd", "rg", "sasa", "hbond"]
    out_dir = OUT / "04_figures" / "01_individual_timeseries"
    for sys_info in SYSTEMS:
        fig, axes = plt.subplots(3, 2, figsize=(7.2, 7.6), sharex=True)
        axes = axes.ravel()
        for ax, metric in zip(axes, metrics):
            data = all_data[(sys_info.pair_id, metric)]
            ax.plot(data["x"], data["value"], color=sys_info.color, lw=0.55, alpha=0.28)
            ax.plot(data["x"], rolling_mean(data["value"], data["x"], 1.0), color=sys_info.color, lw=1.55)
            ax.set_title(METRICS[metric]["title"], pad=5)
            ax.set_ylabel(METRICS[metric]["ylabel"])
            clean_axis(ax)
            if metric == "hbond":
                ax.yaxis.set_major_locator(MaxNLocator(integer=True))
        for ax in axes[-2:]:
            ax.set_xlabel("Time (ns)")
        fig.suptitle(sys_info.label, y=0.995, fontsize=10.5)
        fig.subplots_adjust(hspace=0.34, wspace=0.28, top=0.94)
        save_figure(fig, out_dir / f"{sys_info.pair_id}_core_timeseries")
        plt.close(fig)


def plot_rmsf(all_data: dict[tuple[str, str], pd.DataFrame]) -> None:
    fig, axes = plt.subplots(len(SYSTEMS), 1, figsize=(7.2, 7.8), sharex=False)
    for ax, sys_info in zip(axes, SYSTEMS):
        data = all_data[(sys_info.pair_id, "rmsf")]
        ax.plot(data["x"], data["value"], color=sys_info.color, lw=1.25)
        ax.fill_between(data["x"], data["value"], color=sys_info.color, alpha=0.13, linewidth=0)
        ax.set_ylabel("RMSF (nm)")
        ax.text(0.01, 0.86, sys_info.label, transform=ax.transAxes, ha="left", va="center", fontsize=8.5)
        clean_axis(ax)
    axes[-1].set_xlabel("Residue index")
    fig.subplots_adjust(hspace=0.24)
    save_figure(fig, OUT / "04_figures" / "02_rmsf_profiles_calpha")
    plt.close(fig)


def plot_summary_bars(summary: pd.DataFrame) -> None:
    metrics = ["complex_rmsd", "protein_rmsd", "ligand_rmsd", "rg", "sasa", "hbond"]
    fig, axes = plt.subplots(3, 2, figsize=(7.4, 7.8))
    axes = axes.ravel()
    y_pos = np.arange(len(SYSTEMS))
    labels = ["MAPK14-Pel", "MAPK14-Thy", "PTPRC-Flav", "BCL2-Flav"]
    colors = [s.color for s in SYSTEMS]
    for ax, metric in zip(axes, metrics):
        rows = summary[summary["metric"] == metric].set_index("pair_id").loc[[s.pair_id for s in SYSTEMS]]
        y = rows["final_80_100ns_block_mean"].to_numpy(dtype=float)
        err = rows["final_80_100ns_block_95ci"].to_numpy(dtype=float)
        ax.barh(y_pos, y, xerr=err, capsize=2.5, color=colors, edgecolor="#333333", linewidth=0.45)
        ax.set_title(METRICS[metric]["title"], pad=5)
        ax.set_xlabel(METRICS[metric]["ylabel"])
        ax.set_yticks(y_pos)
        ax.set_yticklabels(labels)
        ax.invert_yaxis()
        clean_axis(ax)
        if metric == "hbond":
            ax.xaxis.set_major_locator(MaxNLocator(integer=True))
    fig.subplots_adjust(hspace=0.42, wspace=0.42, left=0.16)
    save_figure(fig, OUT / "04_figures" / "03_final20ns_block_mean_95ci")
    plt.close(fig)


def plot_fel(all_data: dict[tuple[str, str], pd.DataFrame]) -> None:
    r_const = 0.00831446261815324
    temp = 300.0
    fig, axes = plt.subplots(2, 3, figsize=(8.4, 5.1))
    axes = axes.ravel()
    fel_maps = []
    vmax_values = []
    for sys_info in SYSTEMS:
        rmsd = all_data[(sys_info.pair_id, "protein_rmsd")]
        rg = all_data[(sys_info.pair_id, "rg")]
        merged = pd.merge_asof(
            rmsd.sort_values("x"),
            rg.sort_values("x"),
            on="x",
            direction="nearest",
            tolerance=0.006,
            suffixes=("_rmsd", "_rg"),
        ).dropna()
        x = merged["value_rmsd"].to_numpy(dtype=float)
        y = merged["value_rg"].to_numpy(dtype=float)
        hist, xedges, yedges = np.histogram2d(x, y, bins=45)
        prob = hist / np.nansum(hist)
        with np.errstate(divide="ignore", invalid="ignore"):
            energy = -r_const * temp * np.log(prob)
        energy[np.isfinite(energy)] -= np.nanmin(energy[np.isfinite(energy)])
        energy[~np.isfinite(energy)] = np.nan
        fel_maps.append((sys_info, xedges, yedges, energy))
        vmax_values.append(np.nanpercentile(energy, 98))

    vmax = float(np.nanmax(vmax_values))
    last_mesh = None
    for ax, (sys_info, xedges, yedges, energy) in zip(axes[:-1], fel_maps):
        last_mesh = ax.pcolormesh(xedges, yedges, energy.T, cmap="viridis", shading="auto", vmin=0, vmax=vmax)
        ax.set_title(sys_info.label, pad=5)
        ax.set_xlabel("Protein RMSD (nm)")
        ax.set_ylabel("Rg (nm)")
        clean_axis(ax)
        ax.grid(False)
    for ax in axes[len(fel_maps):-1]:
        ax.axis("off")
    cax = axes[-1]
    cax.clear()
    if last_mesh is not None:
        cbar = fig.colorbar(last_mesh, cax=cax)
        cbar.set_label("Free energy (kJ/mol)")
    fig.subplots_adjust(wspace=0.42, hspace=0.42)
    save_figure(fig, OUT / "04_figures" / "04_fel_rmsd_rg_2d")
    plt.close(fig)


def make_tables(all_data: dict[tuple[str, str], pd.DataFrame]) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    summaries = []
    blocks = []
    for sys_info in SYSTEMS:
        for metric, meta in METRICS.items():
            data = all_data[(sys_info.pair_id, metric)]
            if meta["kind"] != "time":
                continue
            summary, block_rows = full_and_block_stats(sys_info, metric, data)
            summaries.append(summary)
            blocks.extend(block_rows)

    rmsf_rows = []
    for sys_info in SYSTEMS:
        data = all_data[(sys_info.pair_id, "rmsf")]
        top = data.sort_values("value", ascending=False).head(10)
        for _, row in top.iterrows():
            rmsf_rows.append(
                {
                    "pair_id": sys_info.pair_id,
                    "system": sys_info.label,
                    "protein": sys_info.protein,
                    "ligand": sys_info.ligand,
                    "residue_index": int(row["x"]),
                    "rmsf_nm": float(row["value"]),
                }
            )

    return pd.DataFrame(summaries), pd.DataFrame(blocks), pd.DataFrame(rmsf_rows)


def copy_raw_timeseries(all_data: dict[tuple[str, str], pd.DataFrame]) -> None:
    raw_dir = OUT / "02_tidy_timeseries"
    raw_dir.mkdir(parents=True, exist_ok=True)
    for sys_info in SYSTEMS:
        for metric in METRICS:
            data = all_data[(sys_info.pair_id, metric)].copy()
            data.insert(0, "metric", metric)
            data.insert(0, "system", sys_info.label)
            data.insert(0, "pair_id", sys_info.pair_id)
            data.to_csv(raw_dir / f"{sys_info.pair_id}__{metric}.csv", index=False)


def write_report(summary: pd.DataFrame, blocks: pd.DataFrame) -> None:
    lines = [
        "# MD core analysis report",
        "",
        "## Analysis scope",
        "",
        f"- Systems: {len(SYSTEMS)} completed 100 ns protein-ligand MD simulations.",
        "- Trajectories were centered on Protein_UNL, compacted with periodic boundary handling, and fitted to the protein backbone.",
        "- Core metrics: complex RMSD, protein backbone RMSD, ligand RMSD after backbone fitting, C-alpha RMSF, protein Rg, protein SASA, and strict protein-ligand hydrogen bonds.",
        "- Hydrogen bonds used `gmx hbond-legacy` with donor-acceptor distance <= 0.35 nm and angle cutoff 30 degrees. Polar contacts were not used as a substitute.",
        "- Statistics were summarized for the whole 0-100 ns trajectory and for the last 20 ns using four 5 ns block means.",
        f"- 95% confidence intervals were calculated from block means. Cross-system p-values were not calculated because the {len(SYSTEMS)} complexes are different systems rather than independent replicates of one condition.",
        "",
        "## Output files",
        "",
        "- Raw GROMACS outputs: each system's `03_analysis` folder.",
        "- Tidy CSV time series: `12_md_candidates/06_md_analysis/02_tidy_timeseries`.",
        "- Summary tables: `12_md_candidates/06_md_analysis/03_tables`.",
        "- Figures: `12_md_candidates/06_md_analysis/04_figures`.",
        "",
        "## Quick final-20-ns summary",
        "",
    ]
    pivot = summary.pivot_table(
        index="system",
        columns="metric",
        values="final_80_100ns_block_mean",
        aggfunc="first",
    )
    lines.append("```")
    lines.append(pivot.round(3).to_string())
    lines.append("```")
    lines.append("")
    (OUT / "05_reports").mkdir(parents=True, exist_ok=True)
    (OUT / "05_reports" / "md_core_analysis_report.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    configure_style()
    for sub in ["02_tidy_timeseries", "03_tables", "04_figures", "05_reports"]:
        (OUT / sub).mkdir(parents=True, exist_ok=True)

    all_data: dict[tuple[str, str], pd.DataFrame] = {}
    for sys_info in SYSTEMS:
        for metric in METRICS:
            all_data[(sys_info.pair_id, metric)] = metric_series(sys_info, metric)

    summary, blocks, rmsf_top = make_tables(all_data)
    copy_raw_timeseries(all_data)

    tables_dir = OUT / "03_tables"
    summary.to_csv(tables_dir / "md_core_summary_statistics.csv", index=False)
    blocks.to_csv(tables_dir / "md_core_80_100ns_block_statistics.csv", index=False)
    rmsf_top.to_csv(tables_dir / "md_rmsf_top10_residues.csv", index=False)
    with pd.ExcelWriter(tables_dir / "md_core_analysis_tables.xlsx", engine="openpyxl") as writer:
        summary.to_excel(writer, sheet_name="summary_statistics", index=False)
        blocks.to_excel(writer, sheet_name="80_100ns_blocks", index=False)
        rmsf_top.to_excel(writer, sheet_name="rmsf_top10", index=False)

    plot_core_timeseries(all_data)
    plot_individual_timeseries(all_data)
    plot_rmsf(all_data)
    plot_summary_bars(summary)
    plot_fel(all_data)
    write_report(summary, blocks)

    print(f"Finished MD core analysis figures and tables under {OUT}")


if __name__ == "__main__":
    main()
